engines:
  rubocop:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
        javascript:
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.js"
exclude_paths:
- spec/**/*
- vendor/**/*
- db/**/*
